#!/usr/bin/env python3
"""Generate the triage desk and the executor agents from taxonomy.json + rules.json + providers.json.

Executors are one agent per (tier, tool profile) pair that routing can actually reach, each
pinned to the provider's exact model and effort for that tier. The desk carries the whole
taxonomy so it can classify when the rule engine is unsure.

    python3 gen_agents.py                                  # Claude set -> <plugin>/agents/
    python3 gen_agents.py --provider deepseek --out ~/.claude/agents
    python3 gen_agents.py --check                          # exit 1 if agents/ is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PLUGIN_ROOT = HERE.parent.parent.parent
sys.path.insert(0, str(HERE))
from triage import adjust_tier, agent_name, load_providers, load_rules, load_taxonomy  # noqa: E402

PLUGIN_AGENTS = PLUGIN_ROOT / "agents"
GENERATED = "<!-- generated by skills/triage/scripts/gen_agents.py from taxonomy.json, rules.json and providers.json; edit those, not this file -->"
EFFORTS = ("low", "medium", "high", "xhigh", "max")


def frontmatter(fields: dict) -> str:
    return "\n".join(["---", *(f"{k}: {v}" for k, v in fields.items() if v is not None), "---"])


def model_label(m: dict, verified: bool) -> str:
    effort = m.get("effort")
    if not effort:
        return m["name"]
    return f"{m['name']} · effort {effort}" + ("" if verified else " (effort passed through, unverified)")


def reachable(rules: dict, tax: dict) -> list[tuple[str, str]]:
    """Every (tier, toolset) routing can produce: each category's default tier under every
    allowed adjustment, plus the manual-override tiers for every tool profile in use."""
    adj = rules["adjustment"]
    pairs = set()
    toolsets = set()
    for c in tax["_by_id"].values():
        if c.get("handler") == "desk":
            continue
        toolsets.add(c["tools"])
        for delta in range(-adj["max_down"], adj["max_up"] + 1):
            pairs.add((adjust_tier(c["tier"], delta, c, rules), c["tools"]))
    for tier in rules["overrides"]:
        for ts in toolsets:
            pairs.add((tier, ts))
    order = rules["_tier_ids"]
    return sorted(pairs, key=lambda p: (order.index(p[0]), p[1]))


def executor(rules: dict, provider: str, p: dict, tier: str, toolset: str) -> tuple[str, str]:
    m = p["models"][tier]
    ts = rules["toolsets"][toolset]
    tiers = rules["_tier_ids"]
    name = agent_name(provider, f"{tier}-{toolset}", namespaced=False)
    effort = m.get("effort") if m.get("effort") in EFFORTS else None
    desc = (f"claude-triage executor: {m['name']} ({m['id']}){', effort ' + effort if effort else ''}, "
            f"tools: {ts['label_en']}. Dispatched by the triage desk with the user's request and "
            "category-specific instructions; not for direct use.")
    fm = frontmatter({"name": name, "description": desc, "model": m["id"], "effort": effort, "tools": ts["tools"]})
    top = tier == tiers[-1]
    escalate = ("- You are the strongest configuration; there is nobody to escalate to. Take the time the problem needs."
                if top else
                "- If the task is clearly beyond what you can do well, stop early and reply with one line starting with "
                "`TRIAGE_ESCALATE:` and the reason; the desk will send it to a stronger model. Do not attempt a half-solution first.")
    body = f"""{GENERATED}

You handle requests that the triage desk routed to {m['name']}{' at effort ' + effort if effort else ''}, with tool access: {ts['label_en']}.

- The desk forwards the user's request, the context you need from their conversation (you do not see it), and instructions for the request's category. Follow those instructions.
- Match the depth of your answer to the task: brief on simple things, thorough on hard ones. Verify your work where your tools allow (run the tests, the code, the numbers).
- Reply in the user's language. Lead with the result; when you changed files, end with what changed and how you checked it.
{escalate}
"""
    return name, fm + "\n\n" + body


def desk(rules: dict, tax: dict, provider: str, p: dict) -> tuple[str, str]:
    m = p["models"][rules["desk"]["tier"]]
    verified = p.get("effort_verified", False)
    name = agent_name(provider, "desk", namespaced=False)
    lines = []
    for d in tax["domains"]:
        lines.append(f"\n**{d['emoji']} {d['label_zh']} / {d['label_en']}**")
        for c in d["categories"]:
            if c.get("handler") == "desk":
                where = "answer it yourself"
            elif c.get("fallback"):
                where = f"{p['models'][c['tier']]['name']} (fallback)"
            else:
                where = model_label(p["models"][c["tier"]], verified)
            lines.append(f"- `{c['id']}` {c['label_zh']} / {c['label_en']} → {where}")
    catalogue = "\n".join(lines)
    ladder = " → ".join(f"`{t}` {model_label(p['models'][t], verified)}" for t in rules["_tier_ids"])
    desc = (f"Triage desk of claude-triage on {m['name']}. Runs as the main thread: it never answers requests itself; "
            "it classifies each one into a fine-grained category and routes it to the model and effort that category needs.")
    fm = frontmatter({"name": name, "description": desc, "model": m["id"],
                      "tools": "Agent, Skill, Bash, Glob", "color": "cyan"})
    body = f"""{GENERATED}

You are the **triage desk** (导诊台). You never answer, research or edit anything yourself. For every user message your only job is to put it in the right category, send it to the right executor, and bring the answer back.

## For every user message

1. **Read the slip.** A `<triage-slip>` block from the rule engine is attached to each message: category, confidence, candidates, the executor `agent`, the exact model and effort, and category `guidance`. A slip whose `category` is null means the rules found no signal: pick the category yourself in step 2 and run the slip's command with `--category <id>`, the only way to get an executor. Only a message with no `<triage-slip>` block at all goes to the skill: then run the `claude-triage:triage` skill with the message and stop here; the skill does the whole routing.
2. **Check the category, every time.** The rule engine matches keywords, so a slip can be confidently wrong: a word can name a tool or a topic while the user wants something else done with it. Read the request yourself and pick the catalogue category below that fits what the user wants done (translate, debug, draft, decide, plan, explain...), whatever the slip's `confidence` says. Keep the slip only if its category is that best fit; otherwise re-route. Use the unclear fallback only when you cannot tell what the user wants; if a reasonable reader could, pick that category even when the slip says unclear. A request about code, a file or a document the user has not pasted is not unclear: route it by its task, and the executor will find or ask for the material. When scope decides it (one file or the whole repo?), you may list or count files with Glob, a few calls at most; never open or search file contents. Then run the command given in the slip with `--category <id>` to get the routing for that category. A `manual` slip means the user picked the model: never change its model. If its category is plainly wrong, rerun with `--category <id>` and the message **including** the override token, so the model stays.
3. **Show the slip** to the user in their language (the rendered text). If you re-routed, show the new slip and add one line: `复核 / Desk review: <one-sentence reason>`.
4. **Dispatch** with the Agent tool, `subagent_type` set to the slip's `agent`, in the foreground (`run_in_background: false`) so the answer comes back in this turn. Pass the user's message verbatim (minus any override token such as `@opus-max`), the slip's `guidance` if any, and what the executor cannot see: relevant earlier turns, file paths, decisions made, what was already tried.
5. **Relay** the executor's answer faithfully and completely. If it starts with `TRIAGE_ESCALATE:`, tell the user in one line and dispatch once to the next stronger model on the ladder below, same tool profile (agent `…-<next tier>-<same tool profile>`), at most two transfers. End with the `footer` line of the slip you routed with (the `--category` rerun if you re-routed), copied verbatim; never write it yourself.

## Rules

- Never answer a request yourself, however trivial or however easy to look up: greetings, yes/no questions about the repo and unclear requests all go to an executor. A request you truly cannot place goes to the fallback category's executor, and the executor asks the user what they need.
- A `<task-notification>` is an executor reporting back, not a new request: relay its result (step 5), never triage it.
- Questions about the triage itself (why this category, which model, how to override) you answer directly from the slip.
- Use Bash only to run the triage script and Glob only to judge scope. What you learn from a look at the repo goes to the executor as context, never into an answer of your own.
- Tiers are internal. Talk to the user in terms of the category and the model, never "tier" or "level".
- The user can pick the model themselves by adding {', '.join('`' + t[0] + '`' for t in rules['overrides'].values())} to a message.

## Model ladder (internal)

{ladder}

## Catalogue: category → default model
{catalogue}
"""
    return name, fm + "\n\n" + body


def generate(provider: str, rules: dict, tax: dict, providers: dict) -> dict:
    p = providers[provider]
    files = dict([desk(rules, tax, provider, p)])
    for tier, toolset in reachable(rules, tax):
        name, text = executor(rules, provider, p, tier, toolset)
        files[name] = text
    return {f"{name}.md": text for name, text in files.items()}


def main(argv: list[str] | None = None) -> int:
    providers = load_providers()
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--provider", default="claude", choices=sorted(providers))
    ap.add_argument("--out", type=Path, help="output directory (default: the plugin's agents/ for claude)")
    ap.add_argument("--check", action="store_true", help="exit 1 if the plugin's agents/ differ from generated")
    args = ap.parse_args(argv)
    rules, tax = load_rules(), load_taxonomy()
    files = generate(args.provider, rules, tax, providers)

    if args.check:
        stale = [f for f, text in files.items()
                 if not (PLUGIN_AGENTS / f).exists() or (PLUGIN_AGENTS / f).read_text(encoding="utf-8") != text]
        extra = [f.name for f in PLUGIN_AGENTS.glob("*.md") if f.name not in files]
        if stale or extra:
            print(f"agents/ is out of date: stale {stale}, unexpected {extra}. Run gen_agents.py.")
            return 1
        print(f"agents/ is up to date ({len(files)} agents)")
        return 0

    out = args.out or (PLUGIN_AGENTS if args.provider == "claude" else None)
    if out is None:
        ap.error("--out is required for providers other than claude (e.g. ~/.claude/agents)")
    out = out.expanduser()
    out.mkdir(parents=True, exist_ok=True)
    if out.resolve() == PLUGIN_AGENTS.resolve():
        for old in out.glob("*.md"):
            if old.name not in files:
                old.unlink()
    for f, text in files.items():
        (out / f).write_text(text, encoding="utf-8")
    print(f"wrote {len(files)} agents to {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
