#!/usr/bin/env python3
"""Generate the triage desk and clinic agents from rules.json + providers.json.

The plugin ships the Claude set in agents/ (regenerate after editing the
clinics or the Claude models). For another provider, the agents are written
as user- or project-level agents, because the model IDs differ per provider:

    python3 gen_agents.py                                  # Claude set -> <plugin>/agents/
    python3 gen_agents.py --provider deepseek --out ~/.claude/agents
    python3 gen_agents.py --check                          # exit 1 if agents/ is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PLUGIN_ROOT = HERE.parent.parent.parent
sys.path.insert(0, str(HERE))
from triage import DEFAULT_RULES, agent_name, clinic_ids, load_providers, load_rules  # noqa: E402

PLUGIN_AGENTS = PLUGIN_ROOT / "agents"
GENERATED = "<!-- generated by skills/triage/scripts/gen_agents.py from rules.json + providers.json; edit those, not this file -->"


def frontmatter(fields: dict) -> str:
    lines = ["---"]
    for k, v in fields.items():
        if v is not None:
            lines.append(f"{k}: {v}")
    lines.append("---")
    return "\n".join(lines)


def clinic_agent(rules: dict, provider: str, p: dict, index: int) -> tuple[str, str]:
    c = rules["clinics"][index]
    m = p["models"][c["id"]]
    name = agent_name(provider, c["id"], namespaced=False)
    nxt = rules["clinics"][index + 1] if index + 1 < len(rules["clinics"]) else None
    effort = m.get("effort") if m.get("effort") in ("low", "medium", "high", "xhigh", "max") else None
    desc = (f"{c['label_en']} of claude-triage: {m['name']} ({m['id']})"
            f"{', effort ' + effort if effort else ''}. Handles: {c.get('suits_en', c['suits_zh'])}. "
            "Dispatched by the triage desk; not for direct use.")
    fm = frontmatter({"name": name, "description": desc, "model": m["id"], "effort": effort,
                      "color": c.get("color")})
    escalate = (
        f"- If the task turns out to be clearly beyond this clinic, stop early and reply with one line starting with "
        f"`TRIAGE_ESCALATE:` and the reason; the desk will transfer it to the {nxt['label_en']}. "
        "Do not attempt a half-solution first."
        if nxt else
        "- You are the strongest clinic. Take the time the problem needs; there is nobody to escalate to.")
    body = f"""{GENERATED}

You are the **{c['label_en']}** ({c['label_zh']}) of a triage desk, running on {m['name']}.
Requests arrive here because the desk judged them to fit this clinic: {c.get('suits_en', c['suits_zh'])}.

- The desk forwards the user's request together with the context you need from their conversation. Work from that; ask for nothing you can find in the repository yourself.
- Match the depth of your answer to the task: be brief on simple things, thorough on hard ones. Verify your work where you can (run the tests, the linter, or the code).
- Reply in the user's language. Lead with the result; when you changed files, end with what changed and how you checked it.
{escalate}
"""
    return name, fm + "\n\n" + body


def desk_agent(rules: dict, provider: str, p: dict) -> tuple[str, str]:
    m = p["models"][rules["desk"]["model_clinic"]]
    name = agent_name(provider, "desk", namespaced=False)
    rows = []
    for c in rules["clinics"]:
        cm = p["models"][c["id"]]
        eff = cm.get("effort") or "default"
        rows.append(f"| `{c['id']}` | {c['label_en']} / {c['label_zh']} | {cm['name']} (`{cm['id']}`), effort {eff} | "
                    f"`{agent_name(provider, c['id'])}` | {c.get('suits_en', c['suits_zh'])} |")
    table = "\n".join(["| clinic | name | model | agent to dispatch to | suits |", "|---|---|---|---|---|", *rows])
    desc = (f"Triage desk of claude-triage on {m['name']}. Runs as the main thread: it never answers requests itself, "
            "it routes each one to the clinic agent with the right model and effort.")
    fm = frontmatter({"name": name, "description": desc, "model": m["id"], "tools": "Agent, Skill, Bash", "color": "cyan"})
    body = f"""{GENERATED}

You are the **triage desk** (导诊台). You do not answer, research, or edit anything yourself. For every user message your only job is to send it to the right clinic and bring the clinic's answer back.

## Clinics

{table}

## For every user message

1. **Get the slip.** A `<triage-slip>` block computed by the rule engine is attached to each user message. If it is missing, run the `claude-triage:triage` skill with the message instead and stop here; the skill does the whole routing.
2. **Second opinion.** If the slip's `confidence` is `low`, decide the clinic yourself from the table above: pick the cheapest clinic that can clearly do the job well, and only go higher when a wrong answer would be costly. Never change a slip whose confidence is `manual`.
3. **Show the slip** to the user (the rendered text in the block, in their language). If you changed the clinic, update the clinic / model / effort lines and add a line `护士复核 / Desk review: <one-sentence reason>`.
4. **Dispatch** with the Agent tool to the agent named in the table for that clinic. Pass the user's message verbatim (minus any `@clinic` override token), plus what the clinic cannot see: relevant earlier turns, file paths, decisions already made, what was already tried. Clinics do not see this conversation.
5. **Relay** the clinic's answer faithfully and completely; do not shorten or "improve" it. If it starts with `TRIAGE_ESCALATE:`, tell the user in one line and dispatch once to the next clinic down the table (at most two transfers). End with one line: `— {{clinic name}} · {{model}} · effort {{effort}}`.

## Rules

- Never answer the request yourself, even when it looks trivial: trivial requests go to `{rules['clinics'][0]['id']}`.
- Use Bash only to run the triage skill's rule-engine script, never to work on the request.
- You may answer questions about the triage itself (why a clinic was chosen, how to override) directly from the slip.
- The user can force a clinic by adding {', '.join('`@' + x + '`' for x in clinic_ids(rules))} to a message.
"""
    return name, fm + "\n\n" + body


def generate(provider: str, rules: dict, providers: dict) -> dict:
    p = providers[provider]
    files = dict([desk_agent(rules, provider, p)])
    for i in range(len(rules["clinics"])):
        name, text = clinic_agent(rules, provider, p, i)
        files[name] = text
    return {f"{name}.md": text for name, text in files.items()}


def main(argv: list[str] | None = None) -> int:
    providers = load_providers()
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--provider", default="claude", choices=sorted(providers))
    ap.add_argument("--out", type=Path, help="output directory (default: the plugin's agents/ for claude)")
    ap.add_argument("--check", action="store_true", help="exit 1 if the plugin's agents/ differ from generated")
    args = ap.parse_args(argv)
    rules = load_rules(DEFAULT_RULES)
    files = generate(args.provider, rules, providers)

    if args.check:
        stale = [f for f, text in files.items()
                 if not (PLUGIN_AGENTS / f).exists() or (PLUGIN_AGENTS / f).read_text(encoding="utf-8") != text]
        extra = [f.name for f in PLUGIN_AGENTS.glob("*.md") if f.name not in files]
        if stale or extra:
            print(f"agents/ is out of date: stale {stale}, unexpected {extra}. Run gen_agents.py.")
            return 1
        print("agents/ is up to date")
        return 0

    out = args.out or (PLUGIN_AGENTS if args.provider == "claude" else None)
    if out is None:
        ap.error("--out is required for providers other than claude (e.g. ~/.claude/agents)")
    out = out.expanduser()
    out.mkdir(parents=True, exist_ok=True)
    if out.resolve() == PLUGIN_AGENTS.resolve():
        for old in out.glob("*.md"):
            if old.name not in files:
                old.unlink()
    for f, text in files.items():
        (out / f).write_text(text, encoding="utf-8")
        print(f"wrote {out / f}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
