#!/usr/bin/env python3
"""Render docs/taxonomy.md (the readable routing table) from taxonomy.json, rules.json and providers.json.

    python3 gen_docs.py          # write docs/taxonomy.md
    python3 gen_docs.py --check  # exit 1 if it is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from triage import load_providers, load_rules, load_taxonomy  # noqa: E402

OUT = HERE.parent.parent.parent / "docs" / "taxonomy.md"
TOOLS_ZH = {"code": "代码", "write": "文件", "read": "只读"}


def model_cell(m: dict) -> str:
    return f"{m['name']} · {m['effort']}" if m.get("effort") else m["name"]


def render(rules: dict, tax: dict, providers: dict) -> str:
    claude = providers["claude"]["models"]
    tiers = rules["_tier_ids"]
    n = len(tax["_by_id"])
    out = [
        "# 分诊分类表 / Routing taxonomy",
        "",
        "<!-- generated by skills/triage/scripts/gen_docs.py; edit taxonomy.json / rules.json / providers.json instead -->",
        "",
        f"{len(tax['domains'])} 个大类、{n} 个细类。每条请求先被归到一个细类，细类决定默认的模型和思考深度，"
        "再由后台信号微调。用户只看到“类别 → 模型 · 思考深度 · 理由”，不需要选任何档位。",
        "",
        f"{len(tax['domains'])} domains, {n} categories. Each request is put in one category, which sets the default model "
        "and effort; background signals then adjust it. Users see the category, the model and the reason, never a tier.",
        "",
        "分类依据公开的真实使用研究：OpenAI / NBER《How People Use ChatGPT》（2025-09）、Anthropic Clio 与 Economic Index"
        "（2024-12 至 2026-06）、Microsoft《Copilot Usage Report 2025》。",
        "",
        "图例：**工具** 代码＝读写文件、执行命令、联网；文件＝读写文件、联网，不执行命令；只读＝读文件、联网。"
        "**最低 / 最高**＝后台微调不会越过这一配置。",
        "",
        "## 目录",
        "",
    ]
    for d in tax["domains"]:
        out.append(f"- [{d['emoji']} {d['label_zh']} / {d['label_en']}](#{d['id']})（{len(d['categories'])}）")
    out.append("")

    for d in tax["domains"]:
        out += [f'<a id="{d["id"]}"></a>', "", f"## {d['emoji']} {d['label_zh']} / {d['label_en']}", ""]
        if d.get("guidance_en"):
            out += [f"> 专属指令 / Guidance: {d['guidance_en']}", ""]
        grouped = any("group_zh" in c for c in d["categories"])
        head = ("| 小组 | 细类 | 默认模型 · 深度 | 工具 | 最低 / 最高 | id |" if grouped
                else "| 细类 | 默认模型 · 深度 | 工具 | 最低 / 最高 | id |")
        out += [head, "|" + "---|" * (6 if grouped else 5)]
        last_group = None
        for c in d["categories"]:
            if c.get("handler") == "desk":
                model = "导诊台直接回答"
            else:
                model = model_cell(claude[c["tier"]])
            bounds = " / ".join(x for x in (
                f"最低 {model_cell(claude[c['floor']])}" if c.get("floor") else "",
                f"最高 {model_cell(claude[c['ceiling']])}" if c.get("ceiling") else "") if x) or ""
            label = c["label_zh"] + (f"<br><sub>{c['label_en']}</sub>")
            row = f"{label} | {model} | {TOOLS_ZH[c['tools']]} | {bounds} | `{c['id']}` |"
            if grouped:
                g = c.get("group_zh", "")
                out.append(f"| {g if g != last_group else ''} | {row}")
                last_group = g
            else:
                out.append(f"| {row}")
        out.append("")

    out += ["## 后台微调 / Background adjustments", "",
            "| 信号 | 调整 | 示例 |", "|---|---|---|"]
    for m in rules["modifiers"]:
        examples = "、".join(f"`{p}`" for p in m["patterns"][:3])
        out.append(f"| {m['label_zh']} / {m['label_en']} | {m['delta']:+d} | {examples} |")
    comp = rules["computed_modifiers"]
    out.append(f"| {comp['long_input']['label_zh']} / {comp['long_input']['label_en']} | {comp['long_input']['delta']:+d} | "
               f"≥ {comp['long_input']['min_chars']:,} 字符 |")
    out.append(f"| {comp['many_requirements']['label_zh']} / {comp['many_requirements']['label_en']} | "
               f"{comp['many_requirements']['delta']:+d} | ≥ {comp['many_requirements']['min_items']} 条列表项 |")
    adj = rules["adjustment"]
    need = adj["top_tier_needs"]
    out += ["",
            f"- 最多上调 {adj['max_up']} 档、下调 {adj['max_down']} 档，不越过细类的最低 / 最高配置。",
            f"- 最强的 {model_cell(claude[tiers[-1]])} 不直接对应任何细类：只有默认配置不低于 "
            f"{model_cell(claude[need['min_default']])}、且上调至少 {need['min_up']} 档时才会用到，或由用户手动指定。",
            "", "## 模型阶梯（仅后台使用）/ Model ladder (internal)", "",
            "| 档位 | " + " | ".join(p["label_zh"] for p in providers.values()) + " |",
            "|---|" + "---|" * len(providers)]
    for t in tiers:
        out.append(f"| `{t}` | " + " | ".join(f"{p['models'][t]['name']} `{p['models'][t]['id']}`"
                                              + (f" · {p['models'][t]['effort']}" if p['models'][t].get('effort') else "")
                                              for p in providers.values()) + " |")
    out += ["", "第三方厂商的思考深度会传给厂商接口，是否生效尚未验证；benchmark 直连 API 时按各家参数设置（见 `providers.json` 的 `extra_body`）。",
            "", "## 手动指定模型 / Overrides", "", "| 口令 | 模型 |", "|---|---|"]
    for t, tokens in rules["overrides"].items():
        out.append(f"| {' '.join('`' + x + '`' for x in tokens)} | {model_cell(claude[t])} |")
    out.append("")
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    text = render(load_rules(), load_taxonomy(), load_providers())
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print("docs/taxonomy.md is out of date. Run gen_docs.py.")
            return 1
        print("docs/taxonomy.md is up to date")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
